// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SUT23_Labb_3___API.Data;

#nullable disable

namespace SUT23_Labb_3___API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240426124352_Initial Creation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SUT23_Labb_3___API.Models.Interest", b =>
                {
                    b.Property<int>("InterestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestID");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestID = 100,
                            Description = "Programming a big website",
                            Title = "Programming"
                        },
                        new
                        {
                            InterestID = 101,
                            Description = "throwing around people",
                            Title = "Wrestling"
                        },
                        new
                        {
                            InterestID = 102,
                            Description = "Kicking a ball",
                            Title = "Football"
                        },
                        new
                        {
                            InterestID = 103,
                            Description = "Dancing in the moonlight",
                            Title = "Dancing"
                        });
                });

            modelBuilder.Entity("SUT23_Labb_3___API.Models.Link", b =>
                {
                    b.Property<int>("LinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkID"));

                    b.Property<int>("PersonInterestID")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinkID");

                    b.HasIndex("PersonInterestID");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkID = 10,
                            PersonInterestID = 1,
                            Url = "www.youtube.com"
                        },
                        new
                        {
                            LinkID = 11,
                            PersonInterestID = 2,
                            Url = "www.stackoverflow.com"
                        },
                        new
                        {
                            LinkID = 12,
                            PersonInterestID = 3,
                            Url = "www.football.com"
                        },
                        new
                        {
                            LinkID = 13,
                            PersonInterestID = 4,
                            Url = "www.dancing.com"
                        });
                });

            modelBuilder.Entity("SUT23_Labb_3___API.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonID");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            FirstName = "Ermin",
                            LastName = "Husic",
                            PhoneNumber = "0725978237"
                        },
                        new
                        {
                            PersonID = 2,
                            FirstName = "Pär",
                            LastName = "Nilsson",
                            PhoneNumber = "0724596073"
                        },
                        new
                        {
                            PersonID = 3,
                            FirstName = "Oskar",
                            LastName = "Johansson",
                            PhoneNumber = "0727921237"
                        },
                        new
                        {
                            PersonID = 4,
                            FirstName = "Emilia",
                            LastName = "Millesson Nilsson",
                            PhoneNumber = "0726098751"
                        });
                });

            modelBuilder.Entity("SUT23_Labb_3___API.Models.PersonInterest", b =>
                {
                    b.Property<int>("PersonInterestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonInterestID"));

                    b.Property<int>("InterestID")
                        .HasColumnType("int");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("PersonInterestID");

                    b.HasIndex("InterestID");

                    b.HasIndex("PersonID");

                    b.ToTable("PersonInterests");

                    b.HasData(
                        new
                        {
                            PersonInterestID = 1,
                            InterestID = 100,
                            PersonID = 1
                        },
                        new
                        {
                            PersonInterestID = 2,
                            InterestID = 101,
                            PersonID = 3
                        },
                        new
                        {
                            PersonInterestID = 3,
                            InterestID = 102,
                            PersonID = 2
                        },
                        new
                        {
                            PersonInterestID = 4,
                            InterestID = 103,
                            PersonID = 4
                        });
                });

            modelBuilder.Entity("SUT23_Labb_3___API.Models.Link", b =>
                {
                    b.HasOne("SUT23_Labb_3___API.Models.PersonInterest", "PersonInterest")
                        .WithMany("Links")
                        .HasForeignKey("PersonInterestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonInterest");
                });

            modelBuilder.Entity("SUT23_Labb_3___API.Models.PersonInterest", b =>
                {
                    b.HasOne("SUT23_Labb_3___API.Models.Interest", "Interest")
                        .WithMany("PersonInterest")
                        .HasForeignKey("InterestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SUT23_Labb_3___API.Models.Person", "Person")
                        .WithMany("PersonInterest")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SUT23_Labb_3___API.Models.Interest", b =>
                {
                    b.Navigation("PersonInterest");
                });

            modelBuilder.Entity("SUT23_Labb_3___API.Models.Person", b =>
                {
                    b.Navigation("PersonInterest");
                });

            modelBuilder.Entity("SUT23_Labb_3___API.Models.PersonInterest", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
